controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 0.3 #0.5
  min_vel_x: 0.01 #0.01
  max_vel_theta: 6.28 #1.5
  escape_vel: -0.2

  acc_lim_theta: 3.14
  acc_lim_x: 0.1
  acc_lim_y: 0.1

  sim_time: 1.0

  vx_samples: 20.0
  vtheta_samples: 30.0

  pdist_scale: 0.6 #0.6
  gdist_scale: 0.8 #0.8
  occdist_scale: 3.0
  
  yaw_goal_toleranc: 0.1
  xy_goal_tolerance: 0.3
  
  meter_scoring: true

  holonomic_robot: false
