map_type: costmap

obstacle_range: 2.5 # 2.0
raytrace_range: 3.0 # 3.0

#footprint: [[-0.30, 0.30], [0.30, 0.30], [0.30, -0.30], [-0.30, -0.30]]
robot_radius: 0.35 # 0.0
inflation_radius: 0.30 # 0.0
cost_scaling_factor: 20.0

publish_cost_grid_pc: true

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
